apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yaml

patchesStrategicMerge:
- patch-ingress-nginx-controller-deployment.yaml
- patch-ingress-nginx-admission-create-job.yaml
- patch-ingress-nginx-admission-patch-job.yaml
