apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      tolerations:
        - key: cwmc-role
          value: monitoring
          effect: NoSchedule
      containers:
        - name: controller
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
              hostPort: 80
            - containerPort: 443
              name: https
              protocol: TCP
              hostPort: 443
            - containerPort: 8443
              name: webhook
              protocol: TCP
