apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-nginx-admission-create
  namespace: ingress-nginx
spec:
  template:
    spec:
      tolerations:
        - key: cwmc-role
          value: operator
          effect: NoSchedule
        - key: cwmc-role
          value: monitoring
          effect: NoSchedule
