apiVersion: v1
kind: Service
metadata:
  name: acme-ingress-upstream
  namespace: kube-system
spec:
  selector:
    "app.kubernetes.io/name": "rke2-ingress-nginx"
    "app.kubernetes.io/component": "controller"
  ports:
    - port: 80
      targetPort: 80
