apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-edge
data:
  nginx.conf: |
    worker_processes 10;
    pcre_jit on;
    error_log  stderr  error;

    events {
        worker_connections  10240;
    }

    lua_shared_dict prometheus_metrics 16m;

    http {
      include       mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log logs/access.log combined;
      client_body_temp_path /var/run/openresty/nginx-client-body;
      proxy_temp_path       /var/run/openresty/nginx-proxy;
      fastcgi_temp_path     /var/run/openresty/nginx-fastcgi;
      uwsgi_temp_path       /var/run/openresty/nginx-uwsgi;
      scgi_temp_path        /var/run/openresty/nginx-scgi;
      sendfile        on;
      keepalive_timeout  65;
      server_tokens off;
      server {
          listen 9999;
          server_name  _;
          location /metrics {
              content_by_lua_block {
                  local prometheus = require("prometheus").init("prometheus_metrics")
                  prometheus:collect()
              }
          }
      }
    }

    stream {
      resolver __RESOLVER_IP__ valid=30s ipv6=off;
      resolver_timeout 2s;

      server {
        listen 443;
        ssl_preread on;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
        proxy_pass $ssl_preread_server_name:443;
      }

      init_worker_by_lua_block {
          prometheus = require("prometheus").init("prometheus_metrics")
          metric_requests = prometheus:counter("nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
          metric_latency = prometheus:histogram("nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
          metric_response_size = prometheus:histogram(
              "nginx_http_response_size_bytes", "HTTP response size", {"host"},
              { 128, 512, 1024, 4096, 16384, 65536, 262144, 1048576, 4194304, 16777216 }
          )
          metric_request_size = prometheus:histogram(
              "nginx_http_request_size_bytes", "HTTP request size", {"host"},
              { 128, 512, 1024, 4096, 16384, 65536, 262144, 1048576, 4194304, 16777216 }
          )
      }
      log_by_lua_block {
          metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
          metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
          metric_response_size:observe(tonumber(ngx.var.bytes_sent), {ngx.var.server_name})
          metric_request_size:observe(tonumber(ngx.var.request_length), {ngx.var.server_name})
      }
    }

  Corefile: |
    .:5353 {
      auto {
        directory /data/zones (.*)\.db$ {1}
        reload 1s
      }
      cache 30
      errors
      health :8181
      forward . 169.254.20.10
    }
