apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-edge
data:
  nginx.conf: |
    worker_processes 10;
    pcre_jit on;
    error_log  stderr  error;

    events {
        worker_connections  10240;
    }

    stream {
      lua_shared_dict prometheus_metrics 16m;

      init_worker_by_lua_block {
          prometheus = require("prometheus").init("prometheus_metrics")
          metric_connections = prometheus:counter("nginx_stream_connections_total", "Number of Stream connections", {"server_addr"})
      }

      preread_by_lua_block {
          local s = ngx.var.server_addr or "unknown"
          metric_connections:inc(1, {s})
      }

      resolver __RESOLVER_IP__ valid=30s ipv6=off;
      resolver_timeout 2s;

      server {
        listen 443;
        ssl_preread on;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
        proxy_pass $ssl_preread_server_name:443;
      }

      server {
        listen 9999;
        content_by_lua_block {
          local metrics = table.concat(prometheus:metric_data(), "")
          ngx.print("HTTP/1.1 200 OK\r\n")
          ngx.print("Content-Type: text/plain\r\n")
          ngx.print("Content-Length: " .. #metrics .. "\r\n\r\n")
          ngx.print(metrics)
        }
      }
    }

  Corefile: |
    .:5353 {
      auto {
        directory /data/zones (.*)\.db$ {1}
        reload 1s
      }
      cache 30
      errors
      health :8181
      forward . 169.254.20.10
    }
