apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-edge
data:
  nginx.conf: |
    user  nginx;
    worker_processes 10;

    error_log  /var/log/nginx/error.log notice;
    pid        /run/nginx.pid;

    events {
        worker_connections  10240;
    }

    stream {
      resolver __RESOLVER_IP__ valid=30s ipv6=off;
      resolver_timeout 2s;
      server {
        listen 443;
        ssl_preread on;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
        proxy_pass $ssl_preread_server_name:443;
      }
    }

  Corefile: |
    .:5353 {
      auto {
        directory /data/zones (.*)\.db$ {1}
        reload 1s
      }
      cache 30
      errors
      log
      health :8181
      forward . 169.254.20.10
    }
