apiVersion: v1
kind: ConfigMap
metadata:
  name: cdn-edge
data:
  nginx.conf: |
    worker_processes 10;
    pcre_jit on;
    error_log  stderr  error;

    events {
        worker_connections  10240;
    }

    stream {
      lua_shared_dict prometheus_metrics 16m;

      init_worker_by_lua_block {
          prometheus = require("prometheus").init("prometheus_metrics")
          metric_requests = prometheus:counter("nginx_http_requests_total", "Number of HTTP requests", {"host", "status"})
          metric_latency = prometheus:histogram("nginx_http_request_duration_seconds", "HTTP request latency", {"host"})
          metric_response_size = prometheus:histogram(
              "nginx_http_response_size_bytes", "HTTP response size", {"host"},
              { 128, 512, 1024, 4096, 16384, 65536, 262144, 1048576, 4194304, 16777216 }
          )
          metric_request_size = prometheus:histogram(
              "nginx_http_request_size_bytes", "HTTP request size", {"host"},
              { 128, 512, 1024, 4096, 16384, 65536, 262144, 1048576, 4194304, 16777216 }
          )
      }

      log_by_lua_block {
          metric_requests:inc(1, {ngx.var.server_name, ngx.var.status})
          metric_latency:observe(tonumber(ngx.var.request_time), {ngx.var.server_name})
          metric_response_size:observe(tonumber(ngx.var.bytes_sent), {ngx.var.server_name})
          metric_request_size:observe(tonumber(ngx.var.request_length), {ngx.var.server_name})
      }

      resolver __RESOLVER_IP__ valid=30s ipv6=off;
      resolver_timeout 2s;

      server {
        listen 443;
        ssl_preread on;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
        proxy_pass $ssl_preread_server_name:443;
      }

    server {
      listen 9999;
        content_by_lua_block {
          ngx.say("HTTP/1.1 200 OK")
          ngx.say("Content-Type: text/plain")
          ngx.say("")
          ngx.say(table.concat(prometheus:metric_data(), ""))
        }
      }
    }

  Corefile: |
    .:5353 {
      auto {
        directory /data/zones (.*)\.db$ {1}
        reload 1s
      }
      cache 30
      errors
      health :8181
      forward . 169.254.20.10
    }
