apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cdn-edge-nginx
  labels:
    app: cdn-edge-nginx
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: cdn-edge-nginx
  template:
    metadata:
      labels:
        app: cdn-edge-nginx
    spec:
      nodeSelector:
        cwm-iac-worker-role: cdn
      tolerations:
        - key: "cwm-iac-worker-role"
          operator: "Equal"
          value: "cdn"
          effect: "NoExecute"
      volumes:
        - name: nginx-conf
          configMap:
            name: cdn-edge
            items:
              - key: nginx.conf
                path: nginx.conf
      hostNetwork: true
      containers:
        - name: nginx
          image: {{ .Values.cwmIac.openresty.image | quote }}
          env:
            - name: RESOLVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              sed "s/__RESOLVER_IP__/${RESOLVER_IP}:5353/" /etc/nginx/tmpconf/nginx.conf > /etc/nginx/nginx.conf
              exec nginx -g 'daemon off;'
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/tmpconf
