apiVersion: v1
kind: Namespace
metadata:
  name: cdnedgetest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front
  namespace: cdnedgetest
data:
  default.conf: |
    server {
      listen       443 ssl;
      server_name  _;
      ssl_certificate      /certs/tls.crt;
      ssl_certificate_key  /certs/tls.key;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: cdnedgetest
spec:
  selector:
    matchLabels:
      app: front
  replicas: 1
  template:
    metadata:
      labels:
        app: front
    spec:
      tolerations:
        - key: cwm-iac-worker-role
          operator: Equal
          value: system
          effect: NoExecute
      volumes:
        - name: config
          configMap:
            name: front
      containers:
        - name: front
          image: nginx:latest
          command:
            - bash
            - "-c"
            - |
              set -euo pipefail
              mkdir /certs
              openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout certs/tls.key -out certs/tls.crt -subj "/CN=localhost"
              chmod 600 /certs/tls.key /certs/tls.crt
              sed -i 's/worker_processes  auto;/worker_processes  2;/' /etc/nginx/nginx.conf
              exec nginx -g 'daemon off;'
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: cdnedgetest
spec:
  selector:
    app: front
  ports:
    - port: 443
      targetPort: 443
