apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cwm-canal
subjects:
  - kind: ServiceAccount
    name: calico-kube-controllers
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cwm-canal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cwm-canal
rules:
  - verbs: [get, list, watch]
    resources: [namespaces,services]
    apiGroups: [""]
