apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  roles:
    - name: syncer
      policies:
        - p, proj:default:syncer, applications, get, *, allow
        - p, proj:default:syncer, applications, sync, *, allow
