{
 "title": "Minio Debugging",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "MinIO data source", "query": "prometheus" },
   { "name": "ingress_datasource", "label": "Ingress data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "minio nodes / instances",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance,server,version) (minio_software_version_info{job=\"minio-job-node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Minio Inter Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "inter node traffic sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (server,short_server) (\n    label_replace(\n        rate(minio_inter_node_traffic_sent_bytes{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  {
   "title": "inter node traffic received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (server,short_server) (\n    label_replace(\n        rate(minio_inter_node_traffic_received_bytes{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  {
   "title": "inter node traffic dial avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        minio_inter_node_traffic_dial_avg_time{job=\"minio-job-node\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  {
   "title": "inter node traffic total errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (server,short_server) (\n    label_replace(\n        rate(minio_inter_node_traffic_errors_total{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  {
   "title": "inter node traffic dial errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (server,short_server) (\n    label_replace(\n        rate(minio_inter_node_traffic_dial_errors{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  { "title": "Minio S3 Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "s3 traffic sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        rate(minio_s3_traffic_sent_bytes{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  {
   "title": "s3 traffic received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        rate(minio_s3_traffic_received_bytes{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  {
   "title": "s3 requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        rate(minio_s3_requests_total{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  {
   "title": "s3 errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        rate(minio_s3_requests_errors_total{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  {
   "title": "s3 ttfb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        minio_s3_requests_ttfb_seconds_distribution{job=\"minio-job-node\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{short_server}}"
    }
   ]
  },
  { "title": "Minio Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    minio_process_open_fds{job=\"minio-job-node\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "receive bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(minio_process_network_receive_bytes_total{job=\"minio-job-node\"}[5m])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "resident memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    minio_process_resident_memory_bytes{job=\"minio-job-node\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "cpu cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(minio_process_cpu_seconds_total{job=\"minio-job-node\"}[5m])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "transmit bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(minio_process_network_transmit_bytes_total{job=\"minio-job-node\"}[5m])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    minio_process_virtual_memory_bytes{job=\"minio-job-node\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "go routines running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        minio_node_go_routine_total{job=\"minio-job-cluster\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "read syscalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        rate(minio_node_syscall_read_total{job=\"minio-job-cluster\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "write syscalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (short_server) (\n    label_replace(\n        rate(minio_node_syscall_write_total{job=\"minio-job-cluster\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Minio locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "read locks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        minio_locks_read_total{job=\"minio-job-node\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    },
    {
     "title": "write locks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        minio_locks_write_total{job=\"minio-job-node\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Minio Drives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "operations io waiting",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        rate(minio_node_drive_io_waiting{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    },
    {
     "title": "drive availability errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        rate(minio_node_drive_errors_availability{job=\"minio-job-node\"}[5m]),\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    },
    {
     "title": "drive latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        minio_node_drive_latency_us{job=\"minio-job-node\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    },
    {
     "title": "time disk was busy",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        minio_node_drive_perc_util{job=\"minio-job-resource\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    },
    {
     "title": "read speed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        minio_node_drive_reads_kb_per_sec{job=\"minio-job-resource\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    },
    {
     "title": "reads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        minio_node_drive_reads_per_sec{job=\"minio-job-resource\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    },
    {
     "title": "used bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (short_server) (\n    label_replace(\n        minio_node_drive_used_bytes{job=\"minio-job-node\"},\n        \"short_server\", \"$1\", \"server\", \"([^\\\\.]*).*\"\n    )\n)",
       "legendFormat": "{{short_server}}"
      }
     ]
    }
   ]
  },
  { "title": "Nginx Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "avg request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(nginx_ingress_controller_request_duration_seconds_sum{ingress=~\"subdomain.*\"}[5m]))\n/\nsum by (pod) (rate(nginx_ingress_controller_request_duration_seconds_count{ingress=~\"subdomain.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg request size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(nginx_ingress_controller_request_size_sum{ingress=~\"subdomain.*\"}[5m]))\n/\nsum by (pod) (rate(nginx_ingress_controller_request_size_count{ingress=~\"subdomain.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(nginx_ingress_controller_nginx_process_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(nginx_ingress_controller_nginx_process_read_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(nginx_ingress_controller_nginx_process_write_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nginx Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (nginx_ingress_controller_nginx_process_connections{state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reading connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (nginx_ingress_controller_nginx_process_connections{state=\"reading\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "waiting connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (nginx_ingress_controller_nginx_process_connections{state=\"waiting\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "writing connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (nginx_ingress_controller_nginx_process_connections{state=\"writing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "resident memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (nginx_ingress_controller_nginx_process_resident_memory_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (nginx_ingress_controller_nginx_process_virtual_memory_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}