include /etc/nginx/metrics_shared_dict.conf;

init_worker_by_lua_block {
    dofile("/etc/nginx/metrics_init.lua")
}

log_by_lua_block {
    dofile("/etc/nginx/metrics_log.lua")
}

include /etc/nginx/metrics_server.conf;
