apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml

patchesStrategicMerge:
- patch-node-server-daemonset.yaml
- patch-controller-deployment.yaml

patches:
  - target:
      kind: Deployment
      name: controller
    patch: |-
      - op: remove
        path: /status
  - target:
      kind: DaemonSet
      name: node-server
    patch: |-
      - op: remove
        path: /status
