apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-server
  namespace: directpv
spec:
  template:
    spec:
      tolerations:
        - key: cwmc-role
          value: worker
          effect: NoSchedule
