apiVersion: batch/v1
kind: Job
metadata:
  name: cdn-api
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      tolerations:
        - key: cwm-iac-worker-role
          operator: Equal
          value: system
          effect: NoExecute
      restartPolicy: Never
      containers:
      - name: migration
        image: {{ .Values.cdnApiImage | quote }}
        imagePullPolicy: Always
        command:
          - bin/migrate.sh
          - up
        env:
          - name: MIGRATE_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: cdn-db
                key: DB_CONNSTRING
