apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: vmagent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vmagent
  namespaceSelector:
    matchNames:
      - cdn-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
