apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: ${CLUSTER_ISSUER_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              tolerations:
              - key: cwmc-role
                value: monitoring
                effect: NoSchedule
              - key: cwmc-role
                value: operator
                effect: NoSchedule
              - key: cwmc-role
                value: worker
                effect: NoSchedule
