apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
- cluster-issuer.yaml

patchesStrategicMerge:
- patch-cert-manager-cainjector-deployment.yaml
- patch-cert-manager-deployment.yaml
- patch-cert-manager-webhook-deployment.yaml
