name: "Docker build push"
description: "Build and push Docker image"
inputs:
  image_suffix:
    description: 'The image suffix after the repo/org'
    required: true
  build_args:
    description: 'Additional build args to pass to docker build'
    required: false
    default: ''
  context:
    description: 'Build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  deploy_key_b64:
    description: 'Base64 encoded deploy key with write access to the target repo'
    required: false
    default: ''
  deploy_file_path:
    description: 'Path to the file to write the content to in the deploy repo'
    required: false
    default: ''
  deploy_content_prefix:
    description: 'Content to write to the values file in the deploy repo, the full built image will be appended to this'
    required: false
    default: ''
  deploy_commit_message:
    description: 'Commit message for the deploy repo'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/cloudwebmanage/${{ inputs.image_suffix }}:${{ github.sha }}
          ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && format('ghcr.io/cloudwebmanage/{0}:latest', inputs.image_suffix) || '' }}
        cache-from: type=registry,ref=ghcr.io/cloudwebmanage/${{ inputs.image_suffix }}:buildcache-latest
        cache-to: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && format('type=registry,ref=ghcr.io/cloudwebmanage/{0}:buildcache-latest,mode=max', inputs.image_suffix) || '' }}
        build-args: ${{ inputs.build_args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
    - if: ${{ inputs.deploy_key_b64 != '' && inputs.deploy_file_path != '' && inputs.deploy_content_prefix != '' && inputs.deploy_commit_message != '' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: ./actions/deploy
      with:
        deploy_key_b64: ${{ inputs.deploy_key_b64 }}
        file_path: ${{ inputs.deploy_file_path }}
        content: ${{ format('{0}"{1}"', inputs.deploy_content_prefix, IMAGE) }}
        commit_message: ${{ inputs.deploy_commit_message }}
