name: "Docker build push"
description: "Build and push Docker image"
inputs:
  image_suffix:
    description: 'The image suffix after the repo/org'
    required: true
  build_args:
    description: 'Additional build args to pass to docker build'
    required: false
    default: ''
  context:
    description: 'Build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
  deploy_key_b64:
    description: 'Base64 encoded deploy key with write access to the target repo'
    required: false
    default: ''
  deploy_file_path:
    description: 'Path to the file to write the content to in the deploy repo'
    required: false
    default: ''
  deploy_content_template:
    description: 'Content to write to the values file in the deploy repo, use __IMAGE__ as placeholder for the image name'
    required: false
    default: ''
  deploy_commit_message:
    description: 'Commit message for the deploy repo'
    required: false
    default: ''
  test_script:
    description: 'Optional test script to run after building the image but before pushing / deploying'
    required: false
    default: ''
  wait_for_deployment_json:
    description: 'Optional JSON, if set passed to deploy action'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/setup-buildx-action@v3
    - if: ${{ inputs.test_script != '' }}
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/cloudwebmanage/${{ inputs.image_suffix }}:latest
        push: false
        cache-from: type=gha
        build-args: ${{ inputs.build_args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        load: true
    - if: ${{ inputs.test_script != '' }}
      shell: bash
      run: ${{ inputs.test_script }}
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/cloudwebmanage/${{ inputs.image_suffix }}:${{ github.sha }}
          ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && format('ghcr.io/cloudwebmanage/{0}:latest', inputs.image_suffix) || '' }}
          ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')) && format('ghcr.io/cloudwebmanage/{0}:{1}', inputs.image_suffix, github.ref_name) || '' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build_args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
    - if: ${{ inputs.deploy_key_b64 != '' && inputs.deploy_file_path != '' && inputs.deploy_content_template != '' && inputs.deploy_commit_message != '' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      env:
        DEPLOY_CONTENT_TEMPLATE: ${{ inputs.deploy_content_template }}
        IMAGE: ${{ format('ghcr.io/cloudwebmanage/{0}:{1}', inputs.image_suffix, github.sha) }}
      shell: python
      run: |
        import os
        with open(os.getenv("GITHUB_ENV"), "a") as f:
            f.write("DEPLOY_CONTENT<<EOF\n" + os.getenv('DEPLOY_CONTENT_TEMPLATE').replace('__IMAGE__', os.getenv('IMAGE')).strip() + "\nEOF\n")
    - if: ${{ env.DEPLOY_CONTENT != '' }}
      uses: CloudWebManage/cwm-iac/actions/deploy@main
      with:
        deploy_key_b64: ${{ inputs.deploy_key_b64 }}
        file_path: ${{ inputs.deploy_file_path }}
        content: ${{ env.DEPLOY_CONTENT }}
        commit_message: ${{ inputs.deploy_commit_message }}
        wait_for_deployment_json: ${{ inputs.wait_for_deployment_json }}
