name: "Docker build push"
description: "Build and push Docker image"
inputs:
  image_suffix:
    description: 'The image suffix after the repo/org'
    required: true
  build_args:
    description: 'Additional build args to pass to docker build'
    required: false
    default: ''
  context:
    description: 'Build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
    default: 'Dockerfile'
runs:
  using: composite
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/cloudwebmanage/${{ inputs.image_suffix }}:${{ github.sha }}
          ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && format('ghcr.io/cloudwebmanage/{0}:latest', inputs.image_suffix) || '' }}
        cache-from: type=registry,ref=ghcr.io/cloudwebmanage/${{ inputs.image_suffix }}:buildcache-latest
        cache-to: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') && format('type=registry,ref=ghcr.io/cloudwebmanage/{0}:buildcache-latest,mode=max', inputs.image_suffix) || '' }}
        build-args: ${{ inputs.build_args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
