apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: monitoring-kube-state-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vmagent
  namespaceSelector:
    matchNames:
      - minio-tenant-main-metrics
  endpoints:
    - port: 8429
      path: /metrics
      interval: 30s
