apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cwm
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: cwm
    major: 17
  instances: 1
  storage:
    size: 10Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: cwm-postgres-superuser
  affinity:
    tolerations:
      - key: cwm-iac-worker-role
        operator: Equal
        value: system
        effect: NoExecute
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: cwm
spec:
  images:
    # Updated Aug 1, 2025 from https://raw.githubusercontent.com/cloudnative-pg/postgres-containers/main/Debian/ClusterImageCatalog-bookworm.yaml
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.5-20-bookworm@sha256:5f4d5057c1e7e4af27472972ce26d7b8ae10ab838ca2a5baefbfebfd85a50792
