apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: cwm-minio-api-pooler
spec:
  cluster:
    name: cwm
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "100"
  template:
    spec:
      containers: []
      tolerations:
        - key: cwm-iac-worker-role
          operator: Equal
          value: system
          effect: NoExecute
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cwm-minio-api-pooler
spec:
  selector:
    matchLabels:
      cnpg.io/poolerName: cwm-minio-api-pooler
  podMetricsEndpoints:
    - port: metrics
