apiVersion: v1
kind: Service
metadata:
  name: cwm-minio
spec:
    selector: {{ toYaml .Values.config.minioServiceSelector | nindent 4 }}
  ports:
    - name: http-minio
      protocol: TCP
      port: 80
      targetPort: 9000
