apiVersion: v1
kind: Service
metadata:
  name: cwm-minio-console
spec:
  selector: {{ toYaml .Values.config.minioServiceSelector | nindent 4 }}
  ports:
    - name: http-console
      protocol: TCP
      port: 9090
      targetPort: 9090
