apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: low-tier-aws-s3
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: cwm-worker-cluster/{{ .Values.clusterName }}/low-tier-aws-s3
