apiVersion: v1
kind: Service
metadata:
  name: minio-tenant-primary
spec:
  ports:
    - port: 80
      targetPort: 9000
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Values.tenant.tenant.name }}-pool1-0
