apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: tenant
spec:
  configuration:
    name: env-configuration
  credsSecret:
    name: creds
  image: {{ .Values.config.minioImage }}
  mountPath: /export
  requestAutoCert: false
  podManagementPolicy: {{ .Values.config.minioPodManagementPolicy }}
  env:
    - name: MINIO_DOMAIN
      value: {{ .Values.config.minioDomain | quote }}
    - name: MINIO_BROWSER_REDIRECT_URL
      value: https://{{ .Values.config.minioConsoleDomain }}
    - name: MINIO_SERVER_URL
      value: https://{{ .Values.config.minioDomain }}
    - name: MINIO_POLICY_PLUGIN_URL
      value: http://localhost/
    - name: MINIO_IDENTITY_PLUGIN_URL
      value: http://localhost/
  sideCars:
    containers:
      - name: auth
        image: {{ .Values.config.authImage }}
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
        command:
          - gunicorn
          - "-k"
          - "uvicorn.workers.UvicornWorker"
          - "-c"
          - "/usr/local/src/cwm-worker-operator/cwm_worker_operator/minio_auth_plugin/gunicorn_conf.py"
          - "cwm_worker_operator.minio_auth_plugin.app:app"
  pools:
    {{ range .Values.config.pools }}
    - name: {{ .name }}
      servers: {{ .servers }}
      volumesPerServer: {{ .volumesPerServer }}
      tolerations:
        - effect: NoSchedule
          key: cwmc-role
          operator: Equal
          value: worker
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .volumeSize | quote }}
          storageClassName: directpv-min-io
      {{ end }}
