isPrimary: false
allowedPrimaryKey: ""

cwmCdnApi:
  api:
    image: "ghcr.io/cloudwebmanage/cwm-cdn-api:latest"

prometheus:
  server:
    tolerations:
      - key: "cwm-iac-worker-role"
        operator: "Equal"
        value: "system"
        effect: "NoExecute"

    persistentVolume:
      storageClass: longhorn

    retention: "2d"

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: edge-nginx
          metrics_path: /metrics
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              action: keep
              regex: "cdn-edge-nginx"
            - source_labels: [__meta_kubernetes_pod_ip]
              action: replace
              target_label: __address__
              replacement: $1:9999
        - job_name: tenant
          metrics_path: /metrics
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              action: keep
              regex: "tenant"
            - source_labels: [__meta_kubernetes_pod_ip]
              action: replace
              target_label: __address__
              replacement: $1:9999
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
        - job_name: cache-router
          metrics_path: /metrics
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              action: keep
              regex: "router"
            - source_labels: [__meta_kubernetes_namespace]
              action: keep
              regex: "cdn-cache"
            - source_labels: [__meta_kubernetes_pod_ip]
              action: replace
              target_label: __address__
              replacement: $1:9999
        - job_name: cache
          metrics_path: /metrics
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              action: keep
              regex: "cache.*"
            - source_labels: [__meta_kubernetes_namespace]
              action: keep
              regex: "cdn-cache"
            - source_labels: [__meta_kubernetes_pod_ip]
              action: replace
              target_label: __address__
              replacement: $1:9999


  alertmanager:
    enabled: false

  kube-state-metrics:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  prometheus-pushgateway:
    enabled: false
