prometheus:
  server:
    releaseNamespace: false

    ## this is set from tf module to the minio tenant namespace
    ## namespaces to monitor (instead of monitoring all - clusterwide). Needed if you want to run without Cluster-admin privileges.
    # namespaces:
    #   - yournamespace

    tolerations:
      - key: "cwm-iac-worker-role"
        operator: "Equal"
        value: "system"
        effect: "NoExecute"

    persistentVolume:
      storageClass: longhorn

    retention: "2d"

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: minio-tenant-main-bucket-api
          metrics_path: /bucket/api
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_cwm_minio_tenant]
              action: keep
              regex: "true"
            - source_labels: [__meta_kubernetes_pod_ip]
              action: replace
              target_label: __address__
              replacement: $1:9000

  alertmanager:
    enabled: false

  kube-state-metrics:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  prometheus-pushgateway:
    enabled: false
