apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cwm-redis-commander
spec:
  destination:
    namespace: cwm-redis-commander
    server: 'https://kubernetes.default.svc'
  project: cwm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CloudWebManage/cwm-iac
    targetRevision: main
    path: apps/redis-commander
    plugin:
      name: uumpa
