apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cwm-worker-ingress
spec:
  destination:
    namespace: cwm-worker-ingress
    server: 'https://kubernetes.default.svc'
  project: cwm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:CloudWebManage/cwm-worker-ingress.git
    targetRevision: main
    path: helm
    plugin:
      name: uumpa
      env:
        - name: CWM_APP
          value: cwm-worker-ingress
