apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: directpv
spec:
  destination:
    namespace: directpv
    server: 'https://kubernetes.default.svc'
  project: cwm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CloudWebManage/cwm-iac
    targetRevision: main
    path: apps/directpv
