apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cwm-operator
spec:
  destination:
    namespace: cwm-operator
    server: 'https://kubernetes.default.svc'
  project: cwm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CloudWebManage/cwm-iac
    targetRevision: main
    path: apps/cwm-operator
    plugin:
      name: uumpa
      env:
        - name: CWM_APP
          value: cwm-operator
