apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  project: admin
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: git@github.com:CloudWebManage/cwm-iac.git
    targetRevision: main
    path: apps/logging
    plugin:
      name: uumpa
      env:
        - name: HELM_ARGS
          value: --include-crds
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: logging-loki
      jsonPointers:
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
