apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cwm
spec:
  destinations:
    - name: '*'
      namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/CloudWebManage/cwm-worker-ingress
    - https://github.com/CloudWebManage/cwm-iac
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
