apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  template:
    spec:
      containers:
        - name: minio-operator
          env:
            - name: CLUSTER_DOMAIN
              value: cluster.local
            - name: PROMETHEUS_NAMESPACE
              value: monitoring
      tolerations:
        - key: cwmc-role
          value: operator
          effect: NoSchedule
        - key: cwmc-role
          value: monitoring
          effect: NoSchedule
