{{- range $name, $server := .Values.cacheServers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name | quote }}
spec:
  selector:
    app: {{ $name | quote }}
  ports:
    - port: 80
---
{{- end }}
