{{- range $name, $server := .Values.cacheServers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name | quote }}
spec:
  selector:
    app: {{ $name | quote }}
  ports:
    - name: http
      port: 80
    {{- if $.Values.cacheAdmin.enabled }}
    - name: admin
      port: {{ $.Values.cacheAdmin.port }}
      targetPort: admin
    {{- end }}
---
{{- end }}
