apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
spec:
  selector:
    matchLabels:
      app: router
  replicas: 1
  template:
    metadata:
      labels:
        app: router
    spec:
      tolerations:
        - key: cwm-iac-worker-role
          operator: Equal
          value: cdn
          effect: NoExecute
      containers:
        - name: router
          image: {{ .Values.cwmCdnApi.cacheNginx.image | quote }}
          env:
            - name: TYPE
              value: "router"
            - name: NGINX_HTTP_CONFIGS
              value: |
                include /etc/nginx/metrics.conf;
            - name: NGINX_UPSTREAM_CACHE_SERVERS
              value: |
                {{- range $name, $server := .Values.cacheServers }}
                server {{ $name }}:80;
                {{- end }}
