apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- strimzi-namespace.yaml
- strimzi-cluster-operator-0.40.0.yaml
- minio-audit-kafka.yaml
- minio-tenant-main-audit-logs-kafka-topic.yaml
- minio-tenant-main-notify-kafka-topic.yaml

patchesStrategicMerge:
- patch-strimzi-cluster-operator-deployment.yaml
