apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- strimzi-namespace.yaml
- strimzi-cluster-operator-0.40.0.yaml

patchesStrategicMerge:
- patch-strimzi-cluster-operator-deployment.yaml
