tenant:
  tenant:
    name: ""
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2025-04-08T15-41-24Z
      pullPolicy: IfNotPresent
    configSecret:
      name: ""
    metrics:
      enabled: false

loki:
  global:
    dnsService: "kube-dns-upstream"
  loki:
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    storage:
      bucketNames:
        chunks: "loki-chunks"
        ruler: "loki-ruler"
        admin: "loki-admin"
    storage_config:
      aws:
        s3forcepathstyle: true
        s3: ""  # http<s>://<username>:<secret>@<fqdn>:<port>
    querier:
      max_concurrent: 4
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
      retention_period: 120h
  deploymentMode: SimpleScalable
  backend:
    replicas: 1
    tolerations:
      - key: cwm-iac-worker-role
        operator: Equal
        value: system
        effect: NoExecute
  read:
    replicas: 1
    tolerations:
      - key: cwm-iac-worker-role
        operator: Equal
        value: system
        effect: NoExecute
  write:
    replicas: 1
    tolerations:
      - key: cwm-iac-worker-role
        operator: Equal
        value: system
        effect: NoExecute
  chunksCache:
    tolerations:
      - key: cwm-iac-worker-role
        operator: Equal
        value: system
        effect: NoExecute
  gateway:
    dnsConfig:
    tolerations:
      - key: cwm-iac-worker-role
        operator: Equal
        value: system
        effect: NoExecute
  resultsCache:
    tolerations:
      - key: cwm-iac-worker-role
        operator: Equal
        value: system
        effect: NoExecute
