loki:
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    compactor:
      retention_enabled: true
    limits_config:
      retention_period: 720h
    storage:
      type: filesystem
  singleBinary:
    replicas: 1
    tolerations:
      - key: cwmc-role
        value: monitoring
        effect: NoSchedule
    extraVolumes:
      - name: storage
        emptiDir: {}
    extraVolumeMounts:
      - name: storage
        mountPath: /var/loki
    persistence:
      enabled: false
      # loki has problems running on nfs, see https://github.com/grafana/loki/issues/9482#issuecomment-1735265034
      # storageClass: nfs-client
      # enableStatefulSetAutoDeletePVC: false
  grafana-agent-operator:
    tolerations:
      - key: cwmc-role
        value: monitoring
        effect: NoSchedule
  test:
    enabled: false
  monitoring:
    dashboards:
      enabled: false
    rules:
      enabled: false
    serviceMonitor:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
  gateway:
    tolerations:
      - key: cwmc-role
        value: monitoring
        effect: NoSchedule

promtail:
  tolerations:
    - key: cwmc-role
      operator: Exists
      effect: NoSchedule
  extraVolumes:
    - name: varlogjournal
      hostPath:
        path: /var/log/journal
    - name: runlogjournal
      hostPath:
        path: /run/log/journal
    - name: etcmachineid
      hostPath:
        path: /etc/machine-id
  extraVolumeMounts:
    - name: varlogjournal
      mountPath: /var/log/journal
      readOnly: true
    - name: runlogjournal
      mountPath: /run/log/journal
      readOnly: true
    - name: etcmachineid
      mountPath: /etc/machine-id
      readOnly: true
  config:
    snippets:
      extraScrapeConfigs: |
        - job_name: journal
          journal:
            max_age: 12h
            labels:
              job: systemd-journal
          relabel_configs:
            - source_labels: ['__journal__systemd_unit']
              target_label: 'unit'
            - source_labels: ["__journal__hostname"]
              target_label: "hostname"
