apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-loki-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://logging-loki.logging:3100
