name: terraform
on:
  push:
    branches:
      - main
    paths:
      - tfmodules/**
      - .github/workflows/terraform.*
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          ORG_NAME: ${{ secrets.TFC_ORG_NAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          pip install requests==2.32.5
          python .github/workflows/terraform.py "v0.0.0+${GITHUB_SHA}"
