apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      automountServiceAccountToken: true
      containers:
        - name: uumpa
          command: ["/var/run/argocd/argocd-cmp-server"]
          image: ghcr.io/orihoch/uumpa-argocd-plugin/plugin:5db488b17c4346e3a43ea9736a807c81cf4074b0
          env:
            - name: CLUSTER_NAME
              value: "${CLUSTER_NAME}"
            - name: CWMC_DOMAIN
              value: "${CWMC_DOMAIN}"
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: addr
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: role_id
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: secret_id
            - name: VAULT_PATH
              value: "kv/data/${CLUSTER_NAME}"
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /.cache
              name: uumpa-cache
            - mountPath: /tmp
              name: uumpa-temp
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: uumpa-plugin-config
      tolerations:
        - key: cwmc-role
          value: operator
          effect: NoSchedule
        - key: cwmc-role
          value: monitoring
          effect: NoSchedule
      volumes:
        - name: uumpa-cache
          emptyDir: {}
        - name: uumpa-temp
          emptyDir: {}
        - name: uumpa-plugin-config
          configMap:
            name: uumpa-plugin
