apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      automountServiceAccountToken: true
      containers:
        - name: uumpa
          command: ["/var/run/argocd/argocd-cmp-server"]
          image: ghcr.io/cloudwebmanage/cwm-iac/argocd-plugin:856f960cdbc6bfae2762ef276b5b131106db6a92
          env:
            - name: ARGOCD_ENV_INIT_PLUGIN_FUNCTIONS
              value: "cwm_worker_cluster_argocd_plugin:init"
            - name: ARGOCD_ENV_GENERATE_TEMPLATE_PLUGIN_FUNCTIONS
              value: "cwm_worker_cluster_argocd_plugin:generate_template"
            - name: CLUSTER_NAME
              value: "${CLUSTER_NAME}"
            - name: CWMC_DOMAIN
              value: "${CWMC_DOMAIN}"
            - name: ARGOCD_ENV_VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: addr
            - name: ARGOCD_ENV_VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: role_id
            - name: ARGOCD_ENV_VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-approle
                  key: secret_id
            - name: ARGOCD_ENV_VAULT_PATH
              value: "kv/data/${CLUSTER_NAME}"
          envFrom:
            - secretRef:
                name: cwm
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /.cache
              name: uumpa-cache
            - mountPath: /tmp
              name: uumpa-temp
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: uumpa-plugin-config
      tolerations:
        - key: cwmc-role
          value: operator
          effect: NoSchedule
        - key: cwmc-role
          value: monitoring
          effect: NoSchedule
      volumes:
        - name: uumpa-cache
          emptyDir: {}
        - name: uumpa-temp
          emptyDir: {}
        - name: uumpa-plugin-config
          configMap:
            name: uumpa-plugin
